language: scala

script:
   - sbt scripted

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always


services:
  - mongodb